# Generated by Django 5.1.6 on 2025-03-02 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Spotlights', '0001_initial'),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_debut', models.DateField()),
                ('h_fin', models.DateField()),
                ('spot_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Spotlights.spotlight')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Users.user')),
            ],
        ),
    ]
