# Generated by Django 5.1.6 on 2025-03-02 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Spotlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('etat', models.CharField(max_length=100)),
                ('disponible', models.BooleanField()),
            ],
        ),
    ]
